
name: Deploy to EC2

on:
  push:
    branches:
      - Esti-Klain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_ESTIKLAIN}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_ESTIKLAIN }}
          script: |
            # עדכון הקוד מהגיט בשרת
            cd /home/ubuntu/KonditoriaApp
            git checkout Esti-Klain
            git pull origin Esti-Klain
           
            # בנייה והעתקה של הקליינט (בהנחה שהרצת הבילד ב-GitHub)
            # אם את רוצה לבנות ישירות על השרת כדי לחסוך העברת קבצים:
            cd ./react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
           
            # אתחול הסרבר
            sudo systemctl restart konditoria
