name: Deploy to EC2

on:
  push:
    branches:
      - ayalaKastner

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # או הגרסה שאת משתמשת בה

      - name: Build Client
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_AYALAKASTNER }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_AYALAKASTNER }}
          script: |
            # עדכון הקוד מהגיט בשרת
            cd /home/ubuntu
            git checkout ayalaKastner
            git pull origin ayalaKastner
            
            # בנייה והעתקה של הקליינט (בהנחה שהרצת הבילד ב-GitHub)
            # אם את רוצה לבנות ישירות על השרת כדי לחסוך העברת קבצים:
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            
            # אתחול הסרבר
            sudo systemctl restart konditoria
